// Generated by CoffeeScript 2.3.1
(function() {
  window.Pagination = window.Pagination = class Pagination {
    constructor() {
      this.main = new Main();
      this.paginationWrapper = $(".entries_PaginationWrapper");
      this.paginationDiv = $(".entries_pagination");
      this.pageNumber = $(".Page_pageNumber");
      this.btnNext = $(".Page_nextBtn");
      this.btnPrevious = $(".Page_previousBtn");
      this.listingTable = $(".entries_table_body");
      this.tableBody = $("<tobody>");
      this.pageSpan = $(".Page_pageNumber");
      this.currentPage = '';
      this.recordsPerPage = 5;
      this.dataArray = [];
    }

    init() {
      return this.getData();
    }

    getData() {
      this.dataArray = this.main.fetchData();
      return this.totalEntries = this.dataArray.length;
    }

    updateMessage(startIndex, endIndex, totalEntries) {
      return $(".entries_info").text("Showing " + startIndex + " to " + endIndex + " of " + totalEntries + " Entries.");
    }

    updatePageNo(pageNo) {
      return $(".Page_pageNumber").text(pageNo);
    }

  };

}).call(this);
